# PySNMP SMI module. Autogenerated from smidump -f python ARISTA-IF-MIB
# by libsmi2pysnmp-0.1.3 at Tue Jan 31 10:06:37 2017,
# Python version sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

# Imports

( aristaMibs, ) = mibBuilder.importSymbols("ARISTA-SMI-MIB", "aristaMibs")
( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( CounterBasedGauge64, ) = mibBuilder.importSymbols("HCNUM-TC", "CounterBasedGauge64")
( ifIndex, ) = mibBuilder.importSymbols("IF-MIB", "ifIndex")
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "ObjectGroup")
( Bits, Counter32, Gauge32, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Gauge32", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "TimeTicks")

# Objects

aristaIfMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 30065, 3, 15)).setRevisions(("2014-10-09 00:00",))
if mibBuilder.loadTexts: aristaIfMIB.setOrganization("Arista Networks, Inc.")
if mibBuilder.loadTexts: aristaIfMIB.setContactInfo("Arista Networks, Inc.\n\nPostal: 5453 Great America Parkway\n        Santa Clara, CA 95054\n\nTel: +1 408 547-5500\n\nE-mail: snmp@arista.com")
if mibBuilder.loadTexts: aristaIfMIB.setDescription("The MIB module for reporting additional interface statistics\non Arista devices.")
aristaIf = MibIdentifier((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1))
aristaIfTable = MibTable((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1))
if mibBuilder.loadTexts: aristaIfTable.setDescription("This table contains additional interface statistics not\ncontained in the IF-MIB.")
aristaIfEntry = MibTableRow((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1)).setIndexNames((0, "IF-MIB", "ifIndex"))
if mibBuilder.loadTexts: aristaIfEntry.setDescription("An entry containing statistics for a given interface.")
aristaIfCounterLastUpdated = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 1), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfCounterLastUpdated.setDescription("The value of sysUpTime at which the counters in the ifTable and ifXTable\nwere sampled from the hardware.")
aristaIfRateInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 2), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfRateInterval.setDescription("The amount of time over which the aristaIf*Rate values\nare averaged for this interface.")
aristaIfInPktRate = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 3), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfInPktRate.setDescription("The rate, in packets per second, of packets inbound on\nthis interface, averaged over aristaIfRateInterval.")
aristaIfOutPktRate = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 4), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfOutPktRate.setDescription("The rate, in packets per second, of packets outbound on\nthis interface, averaged over aristaIfRateInterval.")
aristaIfInOctetRate = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 5), CounterBasedGauge64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfInOctetRate.setDescription("The rate, in octets per second, of data inbound on\nthis interface, averaged over aristaIfRateInterval.")
aristaIfOutOctetRate = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 6), CounterBasedGauge64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfOutOctetRate.setDescription("The rate, in octets per second, of data inbound on\nthis interface, averaged over aristaIfRateInterval.")
aristaIfRatesLastUpdated = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 7), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfRatesLastUpdated.setDescription("The value of sysUpTime at which the aristaIf*Rate gauges were\nlast calculated.")
aristaIfOperStatusChanges = MibTableColumn((1, 3, 6, 1, 4, 1, 30065, 3, 15, 1, 1, 1, 8), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aristaIfOperStatusChanges.setDescription("The number of times since system boot that ifOperStatus has\nchanged.")
aristaIfConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 30065, 3, 15, 2))
aristaIfGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 30065, 3, 15, 2, 1))
aristaIfCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 30065, 3, 15, 2, 2))

# Augmentions

# Groups

aristaIfAdditionalInformationGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 30065, 3, 15, 2, 1, 1)).setObjects(*(("ARISTA-IF-MIB", "aristaIfOutPktRate"), ("ARISTA-IF-MIB", "aristaIfInPktRate"), ("ARISTA-IF-MIB", "aristaIfRatesLastUpdated"), ("ARISTA-IF-MIB", "aristaIfOutOctetRate"), ("ARISTA-IF-MIB", "aristaIfInOctetRate"), ("ARISTA-IF-MIB", "aristaIfCounterLastUpdated"), ("ARISTA-IF-MIB", "aristaIfOperStatusChanges"), ("ARISTA-IF-MIB", "aristaIfRateInterval"), ) )
if mibBuilder.loadTexts: aristaIfAdditionalInformationGroup.setDescription("A collection of objects providing additional information\nabove and beyond what the IF-MIB provides, applicable to\nall network interfaces.")

# Compliances

aristaIfCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 30065, 3, 15, 2, 2, 1)).setObjects(*(("ARISTA-IF-MIB", "aristaIfAdditionalInformationGroup"), ) )
if mibBuilder.loadTexts: aristaIfCompliance.setDescription("The compliance statement for Arista devices\nthat implement the IF-MIB")

# Exports

# Module identity
mibBuilder.exportSymbols("ARISTA-IF-MIB", PYSNMP_MODULE_ID=aristaIfMIB)

# Objects
mibBuilder.exportSymbols("ARISTA-IF-MIB", aristaIfMIB=aristaIfMIB, aristaIf=aristaIf, aristaIfTable=aristaIfTable, aristaIfEntry=aristaIfEntry, aristaIfCounterLastUpdated=aristaIfCounterLastUpdated, aristaIfRateInterval=aristaIfRateInterval, aristaIfInPktRate=aristaIfInPktRate, aristaIfOutPktRate=aristaIfOutPktRate, aristaIfInOctetRate=aristaIfInOctetRate, aristaIfOutOctetRate=aristaIfOutOctetRate, aristaIfRatesLastUpdated=aristaIfRatesLastUpdated, aristaIfOperStatusChanges=aristaIfOperStatusChanges, aristaIfConformance=aristaIfConformance, aristaIfGroups=aristaIfGroups, aristaIfCompliances=aristaIfCompliances)

# Groups
mibBuilder.exportSymbols("ARISTA-IF-MIB", aristaIfAdditionalInformationGroup=aristaIfAdditionalInformationGroup)

# Compliances
mibBuilder.exportSymbols("ARISTA-IF-MIB", aristaIfCompliance=aristaIfCompliance)
